import Head from 'next/head';
import Header from '../components/header';
import HeroBanner from '../components/hero-banner';
import Projects from '../components/projects';
import Experience from '../components/experience';
import Footer from '../components/footer';
import Contact from '../components/contact';

import { AiOutlineUp } from 'react-icons/ai';

import { useEffect, useState } from 'react';

export default function Home() {
  const [width, setWidth] = useState(0);
  const [scrollHeight, setScrollHeight] = useState(-1);
  const isMobile = width < 768;

  useEffect(() => {
    window.addEventListener("resize", handleWindowSizeChange);
    handleWindowSizeChange();

    window.addEventListener("scroll", getScrollHeight);
    getScrollHeight();

    return () => {
      window.removeEventListener("resize", handleWindowSizeChange);
      window.removeEventListener("scroll", getScrollHeight);
    };
  }, []);

  const handleWindowSizeChange = () => {
    setWidth(window.innerWidth);
  }

  const getScrollHeight = () => {
    const element = document.getElementById('projects');
    const elementPosition = element.getBoundingClientRect().top;
    const offsetPosition = elementPosition + window.pageYOffset;

    setScrollHeight(window.scrollY - offsetPosition);
  }

  const scrollToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: 'smooth'
    });
  }

  const topButtonOffset = scrollHeight < 0 ? 'translate-y-[80px] transition duration-200' : 'translate-y-0 transition duration-200'
  
  return (
    <div>
      <Head>
        <title>Ryan Bonk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/profile-favicon.png" />
      </Head>
      
      <Header isMobile={ isMobile }/>

      <main className='min-h-screen mx-auto max-w-screen-2xl'>
        <HeroBanner />
        <Projects />
        <Experience />
        <Contact />
      </main>

      <div className='flex justify-end'>
        <div className={`${topButtonOffset} w-10 h-10 fixed bottom-4 right-4 bg-blue-300 flex items-center justify-center text-center cursor-pointer`} onClick={() => scrollToTop()} >
          <AiOutlineUp />
        </div>
      </div>
      

      <Footer />
    </div>
  )
};
