import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Header from '../components/header';
import HeroBanner from '../components/hero-banner';
import Projects from '../components/projects';
import Experience from '../components/experience';
import Footer from '../components/footer';
import Contact from '../components/contact';

import { AiOutlineUp } from 'react-icons/ai';

import { useEffect, useState } from 'react';

export default function Home() {
  const [width, setWidth] = useState(0);
  const [scrollHeight, setScrollHeight] = useState(-1);
  const isMobile = width < 768;

  useEffect(() => {
    window.addEventListener("resize", handleWindowSizeChange);
    handleWindowSizeChange();

    window.addEventListener("scroll", getScrollHeight);
    getScrollHeight();

    return () => {
      window.removeEventListener("resize", handleWindowSizeChange);
      window.removeEventListener("scroll", getScrollHeight);
    };
  }, []);

  const handleWindowSizeChange = () => {
    setWidth(window.innerWidth);
  }

  const getScrollHeight = () => {
    const element = document.getElementById('projects');
    const elementPosition = element.getBoundingClientRect().top;
    const offsetPosition = elementPosition + window.pageYOffset;

    setScrollHeight(window.scrollY - offsetPosition);
  }

  const scrollToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: 'smooth'
    });
  }
  
  return (
    <div>
      <Head>
        <title>Ryan Bonk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/profile-favicon.png" />
      </Head>
      
      <Header isMobile={ isMobile }/>

      <main className={`${styles.main}`}>
        <HeroBanner />
        <Projects isMobile={isMobile}/>
        <Experience isMobile={isMobile} />
        <Contact isMobile={isMobile} />
      </main>

      <div className={styles.topButtonContainer}>
        <div className={ scrollHeight < 0 ? `${styles.topButton} ${styles.topBtnOff}` : `${styles.topButton} ${styles.topBtnOn}`} onClick={() => scrollToTop()} >
          <AiOutlineUp />
        </div>
      </div>
      

      <Footer />

      

      


      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
};
