import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Header from '../components/header';
import Bio from '../components/bio';
import HeroBanner from '../components/hero-banner';
import Projects from '../components/projects';
import Experience from '../components/experience';
import Footer from '../components/footer';

import { useEffect, useState } from 'react';

import { Lexend } from '@next/font/google';
import Contact from '../components/contact';


const lexend = Lexend({ subsets: ['latin'] });

export default function Home() {
  const [width, setWidth] = useState(0);
  const [scrollHeight, setScrollHeight] = useState(0);
  const isMobile = width < 768;

  useEffect(() => {
    window.addEventListener("resize", handleWindowSizeChange);
    handleWindowSizeChange();

    window.addEventListener("scroll", getScrollHeight);

    return () => {
      window.removeEventListener("resize", handleWindowSizeChange);
      window.removeEventListener("scroll", getScrollHeight);
    };
  }, []);

  const handleWindowSizeChange = () => {
    setWidth(window.innerWidth);
  }

  const getScrollHeight = () => {
    setScrollHeight(window.scrollY);
  }
  
  return (
    
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header isMobile={ isMobile } scrollHeight={ scrollHeight }/>

      <main className={`${styles.main}`}>
        <HeroBanner lexend={lexend} />
        {/* <Bio lexend={lexend} /> */}
        <Projects />
        <Experience />
        <Contact />
      </main>

      <Footer />

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
};
